### ISSUE TITLE
在TG回复提示成功了，但在后台看不见回复的评论，删除评论也没效果。

### ISSUE THREAD

**Issue by notetoday** [opswill/CommentToTelegram#1]
Typecho是最新版本
PHP是8.1版本

**Comment by opswill** [comment]
检查一下用户uid是不是正确的？
1. 如果uid和你登录后台的用户不一样，你在后台是看不到其他账户的回复的
2. 删除评论也是同理，你无法删除其他用户的评论

**Comment by notetoday** [comment]
uid看了，就是1，没有错

**Comment by opswill** [comment]
通过评论和标记垃圾功能正常吗

**Comment by notetoday** [comment]
通过评论和标记垃圾是正常的，就回复和删除不行🤪

**Comment by notetoday** [comment]
仔细测试了一下，可以删除待审核状态下的评论，如果是后台没开审核功能的评论是无法删除的，然后就是回复通过的评论也是无法回复的

**Comment by opswill** [comment]
通过评论、标记垃圾、删除评论调用的是同一个typecho提供的内置函数，如果通过评论和标记垃圾正常工作，那么删除也应该是正常的。
我能想到的只有telegram bot回调你的博客网络出现问题，才有可能失败。可以检查一下服务器的access log看看，关键字
POST /telegram/comment?do=callback

**Comment by notetoday** [comment]
删除只能删除待审核状态下的评论，不能删除已审核状态下的评论

**Comment by opswill** [comment]
> 仔细测试了一下，可以删除待审核状态下的评论，如果是后台没开审核功能的评论是无法删除的，然后就是回复通过的评论也是无法回复的

这个插件的逻辑是，评论提交后默认应该是待审核状态，不是审核状态的评论是无法管理的。需要先管理评论，也就是 通过/删除/标记垃圾，只有通过的评论才能回复。
这一点是readme的使用建议第一点，我的初衷是只通过这一个插件来获取评论通知和管理评论，所以所有评论默认都是要审核的。

**Comment by notetoday** [comment]
> 
> 
> 
> 
> 
> 
> > 仔细测试了一下，可以删除待审核状态下的评论，如果是后台没开审核功能的评论是无法删除的，然后就是回复通过的评论也是无法回复的
> 
> 
> 
> 这个插件的逻辑是，评论提交后默认应该是待审核状态，不是审核状态的评论是无法管理的。需要先管理评论，也就是 通过/删除/标记垃圾，只有通过的评论才能回复。
> 
> 这一点是readme的使用建议第一点，我的初衷是只通过这一个插件来获取评论通知和管理评论，所以所有评论默认都是要审核的。

这样的话，那就只有回复无法使用

**Comment by opswill** [comment]
你试一下先将所有的评论设置为需要审核，然后在telegram通知上通过评论，然后在回复

**Comment by notetoday** [comment]
试过了，不行的

**Comment by notetoday** [comment]
回复的请求也是do=callback吗？我使用回复的时候看日志，请求的是这个

**Comment by opswill** [comment]
> 回复的请求也是do=callback吗？我使用回复的时候看日志，请求的是这个

所有操作都是这个，post过来的内容中有区别

**Comment by notetoday** [comment]
后台依然没有回复的内容
